[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 커스텀 도메인 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 보안 헤더
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 도메인 리다이렉트
[[redirects]]
  from = "https://phoenix-dentala.netlify.app"
  to = "https://phoenixai-agent.site"
  status = 301
  force = true

[[redirects]]
  from = "https://www.phoenix-dentala.netlify.app"
  to = "https://www.phoenixai-agent.site"
  status = 301
  force = true 